# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
- repo: https://github.com/psf/black
  rev: 23.7.0
  hooks:
  - id: black
- repo: local
  hooks:
  - id: pylint
    name: pylint
    entry: pylint
    language: system
    types: [python]
    args:
      [
        "--rcfile=.pylintrc",
        "--errors-only",
        "--reports=n"
      ]
    files: "^src/"
exclude: "^(static|venv|src/helfertool/static/helfertool/vendor|src/helfertool/static/helfertool/theme/bootstrap)/"
